# fly.toml app configuration file generated for blue-sun-4088 on 2023-09-10T23:27:07-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blue-sun-4088"
primary_region = "ams"

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = "8080"
  LOG_LEVEL = "debug"
  FLASK_DEBUG = 1
